[package]
name = "storage"
version = "6.0.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
log = "*"
log4rs = { version = "*", features = ["default", "gzip"] }
clap = "3.0.0-beta.2"
git-version = "*"
tonic = "*"
prost = "*"
tokio = { version = "*", features = ["full"] }
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto", branch = "full_block_store_dev" }
rocksdb = "*"
hex = "*"
libsm = "0.4"

[[bin]]
name = "bench"
path = "benches/main.rs"

[dev-dependencies]
tempfile = "*"
quickcheck = "*"
rand = "0.8"
minitrace = { git = "https://github.com/tikv/minitrace-rust.git" }
minitrace-jaeger = { git = "https://github.com/tikv/minitrace-rust.git" }
minitrace-macro = { git = "https://github.com/tikv/minitrace-rust.git" }

[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1

