[package]
name = "storage"
version = "6.1.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
log = "0.4.14"
log4rs = { version = "1.0.0", features = ["default", "gzip"] }
clap = "3.0.0-beta.2"
git-version = "0.3.4"
tonic = "0.5.0"
prost = "0.8.0"
tokio = { version = "1.8.1", features = ["full"] }
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto", branch = "v6.1.0" }
rocksdb = "0.16.0"
hex = "0.4.3"
libsm = "0.4"

[[bin]]
name = "bench"
path = "benches/main.rs"

[dev-dependencies]
tempfile = "3.2.0"
quickcheck = "1.0.3"
rand = "0.8"
minitrace = { git = "https://github.com/tikv/minitrace-rust.git" }
minitrace-jaeger = { git = "https://github.com/tikv/minitrace-rust.git" }
minitrace-macro = { git = "https://github.com/tikv/minitrace-rust.git" }

[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1

